### ISSUE TITLE
在Docker中运行hustoj

### ISSUE THREAD

**Issue by muzea** [muzea/note#5]
本文仅提供一个运行示例，其中很多做法是**错误**的，仅用于展示hustoj是可以在Docker中的。
使用的数据均存放在`/opt/hustoj` （需要自行创建）。

我们创建一个`docker-compose.yml`文件

```yml
version: '3'

services:

  web:
    container_name: hustoj-web
    image: woodenfish42/hustoj-web-docker
    volumes:
      - "/opt/hustoj/config/db_info.inc.php:/www/include/db_info.inc.php"
      - "/opt/hustoj/data:/home/judge/data"
    ports:
      - "80:80"
    restart: always

  judge:
    container_name: hustoj-judge
    image: woodenfish42/hustoj-judge
    volumes:
      - "/opt/hustoj/config/judge.conf:/home/judge/etc/judge.conf"
      - "/opt/hustoj/data:/home/judge/data"
    restart: always
```

我们需要`/opt/hustoj`有如下结构
```
.
├── config
│   ├── db_info.inc.php
│   └── judge.conf
└── data
```

其中`judge.conf`为 https://github.com/zhblue/hustoj/blob/master/trunk/install/judge.conf 这个文件，你需要修改其中的 `OJ_USER_NAME` `OJ_PASSWORD` 到你实际的数据库配置，并将`OJ_COMPILE_CHROOT`与`OJ_SHM_RUN`设置成0。

其中`db_info.inc.php`为 https://github.com/zhblue/hustoj/blob/master/trunk/web/include/db_info.inc.php 这个文件，你需要修改其中的 `$DB_USER` `$DB_PASS` 到你实际的数据库配置。

我们需要给`/opt/hustoj/data`一些特殊的权限，执行`sudo chmod 777 /opt/hustoj/data`。

然后在有 `docker-compose.yml` 这个文件位置的地方执行 `docker-compose up -d`，即可。
